### ISSUE TITLE
On Mobile Functionality

### ISSUE THREAD

**Issue by arjuna-dev** [abhinavNehra/get-selected-text#1]
Hi Abhinav, congratulations on the library, I am using it on a small project. It would be nice if it could be used on mobile devices as well.

Thanks!

**Comment by abhinavNehra** [comment]
Okay @arjuna-dev  I will look into it
Thanks for the suggestion

**Comment by abhinavNehra** [comment]
It is now supporting mobile also

**Comment by arjuna-dev** [comment]
> It is now supporting mobile also

Thanks, good job!
