### ISSUE TITLE
How to unmark

### ISSUE THREAD

**Issue by ChuchoPV** [abhinavNehra/get-selected-text#3]
I have this code 
` <div
          style={{
            zIndex: "99",
            border: "1px solid black",
            minWidth: 400,
          }}
          id="stuffdiv"
          contenteditable="true"
          ref={stuffDiv}
        >
          <TextSelector
            events={[
              {
                text: "Mark",
                handler: (e) => console.log(e),
              },
              {
                text: "Unmark",
                handler: (text) => console.log(text),
              },
            ]}
            color={"green"}
            colorText={true}
          />
        </div>`

I'm trying to catch everything that the user writes, but in some cases the. user might want to unmark a selection. How could this be done?

**Comment by abhinavNehra** [comment]
Hi @ChuchoPV 

Sorry I didn't add this functionality yet.
If it is not urgent I will try to add this functionality today evening Indian time

**Comment by ChuchoPV** [comment]
No worry. I have been trying to modify it by myself. If you wanted to, you could let me do it and then I will make a pull Request and if you are not agree I will wait for your approach. What you say?

**Comment by abhinavNehra** [comment]
Sure, please try it and also mail me if you have any questions

**Comment by abhinavNehra** [comment]
Hey @ChuchoPV 

I have updated the library with remove function, please inform me if I you need any more help

**Comment by ChuchoPV** [comment]
Great! That's awesome. Let me see.
Thank you very much.

**Comment by AntoRichard** [comment]
Can you update the docs how to add the remove function

**Comment by abhinavNehra** [comment]
@AntoRichard  Yes sure, I totally missed that 😬😬

**Comment by abhinavNehra** [comment]
Done @AntoRichard,  please check
