### ISSUE TITLE
Demo doesn't work on iOS 

### ISSUE THREAD

**Issue by mrtronje** [abhinavNehra/get-selected-text#4]
The demo (netlify) doesn't work properly on iOS - only the native selection popover from iOS is shown.

**Comment by abhinehra** [comment]
Hi @mrtronje 
Thanks for informing me about this. Let me check this issue on iphone and will inform you about the solution as soon as possible

**Comment by abhinehra** [comment]
Hi @mrtronje 
Thanks for informing me about this. I think i didn't updated the demo link on netlify. So if it is needed in emergency then  please can you check after installing it on your side. and inform me about it.

**Comment by mrtronje** [comment]
@abhinavNehra thank you - it works 🎉 Sent a GitHub Star 🙂
